apiVersion: v1
kind: Service
metadata:
  name: textlab-backend
  namespace: textlab
spec:
  selector:
    app: textlab-backend
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
  type: ClusterIP

